In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import os

In [2]:
root = '../results'
names = ['simden', 'varden', 'uniform']

In [3]:
dict_data = []
data_names = os.listdir(root)
for name in names:
    for data_name in data_names:
        if not name in data_name: continue
        run = int(data_name[-1:])
        print(f'reading {data_name}')
        for item in os.listdir(os.path.join(root, data_name)):
            if not item.endswith('.txt'): continue
            with open(os.path.join(root, data_name, item)) as f:
                lines = f.readlines()
            if len(lines) != 3: continue
            nums = [float(line[:-1]) for line in lines]
            file_name = item.split('.')[0]
            alg_name = file_name.split('_')[0]
            r = int(file_name.split('_')[1])
            n = int(file_name.split('_')[2])
            thread = int(file_name.split('_')[3])
            dict_data.append({'name':alg_name, 'r':r, 'n':n, 'thread':thread, 'run':run, 'part':'density computation', 'time':nums[0]})
            dict_data.append({'name':alg_name, 'r':r, 'n':n, 'thread':thread, 'run':run, 'part':'dependent point finding', 'time':nums[1]})
            dict_data.append({'name':alg_name, 'r':r, 'n':n, 'thread':thread, 'run':run, 'part':'single linkage clustering', 'time':nums[2]})
df = pd.DataFrame.from_records(dict_data)

reading simden1
reading simden2
reading simden3
reading varden1
reading varden2
reading varden3
reading uniform2
reading uniform3
reading uniform1

In [4]:
df

         name    r        n  thread  run                       part      time
0     fenwick  100    10000      30    1        density computation  0.001568
1     fenwick  100    10000      30    1    dependent point finding  0.002309
2     fenwick  100    10000      30    1  single linkage clustering  0.000122
3     fenwick  100    10000       2    1        density computation  0.011397
4     fenwick  100    10000       2    1    dependent point finding  0.006319
...       ...  ...      ...     ...  ...                        ...       ...
8311  fenwick  100  1000000       2    1    dependent point finding  1.513910
8312  fenwick  100  1000000       2    1  single linkage clustering  0.005971
8313   static   30   100000       2    1        density computation  0.293269
8314   static   30   100000       2    1    dependent point finding  0.061467
8315   static   30   100000       2    1  single linkage clustering  0.000616

[8316 rows x 7 columns]

In [5]:
def drop_and_sum(df, column):
    if column not in df.columns: return df
    df = df.drop([column], axis=1)
    columns = list(df.columns)
    columns.remove('time')
    df = df.groupby(columns).sum()
    return df.reset_index()

In [6]:
df = drop_and_sum(df, 'run')
df['time']/=3

In [7]:
df=df.loc[df['r']==30]

In [8]:
df.head()

        name   r     n  thread                       part      time
105  fenwick  30  1000       1        density computation  0.003057
106  fenwick  30  1000       1    dependent point finding  0.001759
107  fenwick  30  1000       1  single linkage clustering  0.000012
108  fenwick  30  1000       2        density computation  0.001985
109  fenwick  30  1000       2    dependent point finding  0.001296

In [9]:
df.to_csv('../data.csv')